# Admin

Here is some stuff admins should know how to do.

## Giving User Permissions {.unnumbered}

## Reviewing a Dataset {.unnumbered}

## Deleting Datasets/Groups/Organizations {.unnumbered}

## Restoring a Deleted User {.unnumbered}
When a user is deleted from the website, their information remains in the database with the `state` field set to `deleted`. To reactivate the user, you must set this field to `active` in the database.  

1. Enter the `acep-db-cont` docker container  
    - `> docker exec -it acep-db-cont /bin/bash`  
2. Access the postgres database  
    - `> psql -U postgres`  
3. List all the databases and connect to the ckandb database.
    - `> \l`
    - `> \c ckandb`
4. List all the tables and list the columns of the user table.
    - `> \d`
    - `> \d user`
5. List all the users in the user table.
    - `> SELECT * FROM public.user`
6. Find the deleted user with the username [username].
    - `> SELECT id, name, email, state FROM public.user WHERE name = ‘[username]’`
7. Update the user’s state field.
    - `> UPDATE public.user SET state = ‘active’ WHERE name = ‘[username]’`
8. Find the user again and ensure that the state field is set to active.
    - `> SELECT id, name, email, state FROM public.user WHERE name = ‘[username]’`
