# Metadata Walkthrough {.unnumbered}
A detailed walkthrough of the metadata fields available.

## Dataset Fields
*required field

### Title*
A descriptive title for the dataset.

### Description*
A free-form description of the dataset.

### Keywords
Keywords that describe the dataset.  
Standardized vocabulary TBD

### Contact Points*
Individuals connected to the creation or curation of the dataset. An email address is not required. This includes the following roles:  

- __Creator__: primarily responsible for the content of the dataset  
- __Contributor__: made contributions to the dataset  
- __Editor__: helped prepare the dataset for publication

### Publisher*
The entity responsible for making the dataset available.  
ACEP is the default value. If the publisher is another entity, or if you would like to enter a custom value for one of the fields, select Other and enter information into the provided text box.

### License*
A legal document under which the dataset is made available.

### Organization*
The organization the dataset falls under, either __ACEP Internal Use__ or __ACEP Open Data__.

### Visibility
The visibility of the dataset: __private__ for internal use or under-review datasets and __public__ for reviewed/published datasets.

### Landing Page
A webpage where one can gain access to the dataset or more information about the dataset.

### Release Date*
Enter the date of the dataset's entry to the data catalog.

### Modification Date*
Enter the most recent date of change to the dataset entry.

### Version
An indicator of the version of the dataset.

### Version Notes
A description of changes between the current and previous verion of the dataset.

### Identifier
A unique identifier of the dataset.

### Provenance
The origin and history of the dataset.  
Include the filename of a README or other narrative document that describes the origin of the data and the processing steps employed to get to this posted version. Optionally include changes of ownership, custody, or responsibility. If brief, this information can be included in this free text field instead of in a separate document.  
More info: [https://www.go-fair.org/fair-principles/r1-2-metadata-associated-detailed-provenance/](https://www.go-fair.org/fair-principles/r1-2-metadata-associated-detailed-provenance/)  

### Type
The nature or genre of the dataset.

### Temporal Coverage
The temporal period(s) covered by the dataset.
Enter the begin and end dates for the temporal period(s) covered by the dataset. If there is a period of missing or suspect data in the dataset, you can enter it as a separate temporal coverage and make a comment in the Notes section to explain the issue.

> Warning: If there is no temporal coverage to enter, the field must be deleted.

### Spatial Coverage
The geographical area(s) covered by the dataset.

### Language
The language(s) of the dataset.

### Documentation
A page or document about the dataset. 

### Conforms to
An established standard to which the dataset conforms.

### Is referenced by
A related resource that references, cited, or otherwise points to the dataset.

### URI

## Resource Fields
### Name*
A descriptive name for the resource.

### Description*
A free-form description of the resource.

### Format
The file format of the resource. This can be detected automatically.

### GitHub Repo
If the resource is a link to a GitHub repository, select True. This will allow the addition of a GitHub repository view that displays the repository's statistics.

### Status
The current stage of the resource in the workflow.

### License
A legal document under which the resource is made available.

### Access URL 
A URL where one can access the resource.

### Download URL 
A URL where one can download the resource.

### Release Date*
The date of formal issuance/publication of the resource.

### Modification Date*
The most recent date of change/update/modification to the resource entry.

### Language
The laguage(s) of the metadata or textual values of the resource. 

### Documentation
A page or document about the resource. 

### Conforms to
An established standard to which the resource conforms. 

### Access Services
A data service that gives access to the resource.

### URI